services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - private_network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - private_network
      
  users_db:
    image: postgres:16
    container_name: users_db
    environment:
      - POSTGRES_DB=${KEY_POSTGRES_USERS_DB}
      - POSTGRES_USER=${KEY_POSTGRES_USERS_USER}
      - POSTGRES_PASSWORD=${KEY_POSTGRES_USERS_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - private_network

  orders_db:
    image: postgres:16
    container_name: orders_db
    environment:
      - POSTGRES_DB=${KEY_POSTGRES_ORDERS_DB}
      - POSTGRES_USER=${KEY_POSTGRES_ORDERS_USER}
      - POSTGRES_PASSWORD=${KEY_POSTGRES_ORDERS_PASSWORD}
    ports:
      - "5433:5432" 
    volumes:
      - orders_data:/var/lib/postgresql/data
    networks:
      - private_network

  inventory_db:
    image: postgres:16
    container_name: inventory_db
    environment:
      - POSTGRES_DB=${KEY_POSTGRES_INVENTORIES_DB}
      - POSTGRES_USER=${KEY_POSTGRES_INVENTORIES_USER}
      - POSTGRES_PASSWORD=${KEY_POSTGRES_INVENTORIES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - inventory_data:/var/lib/postgresql/data
    networks:
      - private_network

  redis_cache:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - private_network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - DB_HOST=users_db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://users_db:5432/users
      - SPRING_DATASOURCE_USERNAME=${KEY_POSTGRES_USERS_USER}
      - SPRING_DATASOURCE_PASSWORD=${KEY_POSTGRES_USERS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - kafka
      - users_db
    networks:
      - private_network
      - public_network

  order-service:
    build: ./order-service
    container_name: order-service
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - DB_HOST=orders_db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://orders_db:5432/orders
      - SPRING_DATASOURCE_USERNAME=${KEY_POSTGRES_ORDERS_USER}
      - SPRING_DATASOURCE_PASSWORD=${KEY_POSTGRES_ORDERS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - kafka
      - orders_db
    networks:
      - private_network
      - public_network
  
  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - DB_HOST=inventory_db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://inventory_db:5432/inventories
      - SPRING_DATASOURCE_USERNAME=${KEY_POSTGRES_INVENTORIES_USER}
      - SPRING_DATASOURCE_PASSWORD=${KEY_POSTGRES_INVENTORIES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - kafka
      - inventory_db
    networks:
      - private_network
      - public_network

  ecommerce-frontend:
    build: ./ecommerce-frontend
    container_name: ecommerce-frontend
    volumes:
      - frontend_dist:/dist
    healthcheck:
      test: ["CMD", "test", "-f", "/dist/index.html"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - public_network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      ecommerce-frontend:
        condition: service_completed_successfully
      auth-service:
        condition: service_started
      order-service:
        condition: service_started
      inventory-service:
        condition: service_started
    networks:
      - public_network
      - private_network

networks:
  private_network:
    driver: bridge
  public_network:
    driver: bridge

volumes:
  postgres_data:
  orders_data:
  inventory_data:
  redis_data:
  frontend_dist: