services:
  users_db:
    image: postgres:16
    container_name: users_db
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - private_network

  redis_cache:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - private_network

networks:
  private_network:
    driver: bridge
  public_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: