spring.application.name=order-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/orders
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.key-serialize=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-serialize=org.apache.kafka.common.serializer.JsonDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*


# Security
api.security.token.secret=${JWT_SECRET:my-secret-key}