spring.application.name=inventory-service
server.port=8083

# PostgreSQL (Confirme se a porta 5434 é a do container de Inventário)
spring.datasource.url=jdbc:postgresql://localhost:5434/inventories
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Kafka Consumer
spring.kafka.consumer.group-id=inventory-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Mapeamento: O que este serviço ESCUTA (ele escuta a criação do pedido)
spring.kafka.consumer.properties.spring.json.type.mapping=orderCreated:com.example.inventory_service.infra.kafka.events.OrderCreatedEvent

# Kafka Producer (O que este serviço ENVIA)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Security
api.security.token.secret=${JWT_SECRET:my-secret-key}

# Cache Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379